# List the start-up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install Modular & Mojo
    before: |
      eval $(command gp env -e)
    command: |
      curl https://get.modular.com | MODULAR_AUTH=$MODULAR_AUTH sh -
      modular install mojo
      echo 'export MODULAR_HOME="/home/gitpod/.modular"' >> ~/.zshrc
      echo 'export PATH="/home/gitpod/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
      source ~/.zshrc

vscode:
  extensions:
    - "modular-mojotools.vscode-mojo"
    - "ms-python.python"