[project]
authors = ["Cyrill <cyrill.zadra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "mojo-playground"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
tests = "mojo tests.mojo"

[dependencies]
max = ">=24.5.0,<25"
