[project]
authors = ["Cyrill <cyrill.zadra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "mojo-playground"
platforms = ["linux-64"]
version = "0.1.0"

[feature.cuda]
system-requirements = { cuda = "12" }
channels = ["nvidia"]

[feature.cuda.dependencies]
cuda-toolkit = "12.*" # for compute-sanitizer etc.

#[feature.cuda.pypi-dependencies]
#torch = { version = "==2.7.1", index = "https://download.pytorch.org/whl/cu128" }

[environments]
cuda = { features = ["cuda"] }
default = { features = ["cuda"] }

[tasks]

gpu = "mojo gpu/gpu-hello.mojo"

tests = "mojo tests.mojo"

[dependencies]
max = "*"
