name: Run Mojo tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Magic
      run: |
        curl -ssL https://magic.modular.com/| bash

    - name: Execute 'magic shell'
      run: |
        source $HOME/.bash_profile
        magic run tests

    - name: Run tests
      run: mojo tests.mojo
