name: Run Mojo tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Pixi
      run: |
        curl -fsSL https://pixi.sh/install.sh | sh

    - name: Run tests
      run: |
        pixi run tests
