name: Run Mojo tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Magic
      run: |
        curl -ssL https://magic.modular.com/27b23104-fbed-4fb6-a5ef-345288e29a79 | bash

    - name: Execute 'magic shell'
      run: |
        magic shell

    - name: Run tests
      run: mojo tests.mojo
